/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId.index'
import { Route as ProjectIdAgentsNewRouteImport } from './routes/$projectId.agents.new'
import { Route as ProjectIdAgentsAgentIdRouteImport } from './routes/$projectId.agents.$agentId'

const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdAgentsNewRoute = ProjectIdAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdAgentsAgentIdRoute = ProjectIdAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/agents/$agentId': typeof ProjectIdAgentsAgentIdRoute
  '/$projectId/agents/new': typeof ProjectIdAgentsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/agents/$agentId': typeof ProjectIdAgentsAgentIdRoute
  '/$projectId/agents/new': typeof ProjectIdAgentsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/agents/$agentId': typeof ProjectIdAgentsAgentIdRoute
  '/$projectId/agents/new': typeof ProjectIdAgentsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/$projectId/'
    | '/$projectId/agents/$agentId'
    | '/$projectId/agents/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$projectId'
    | '/$projectId/agents/$agentId'
    | '/$projectId/agents/new'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/$projectId/'
    | '/$projectId/agents/$agentId'
    | '/$projectId/agents/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/agents/new': {
      id: '/$projectId/agents/new'
      path: '/agents/new'
      fullPath: '/$projectId/agents/new'
      preLoaderRoute: typeof ProjectIdAgentsNewRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/agents/$agentId': {
      id: '/$projectId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/$projectId/agents/$agentId'
      preLoaderRoute: typeof ProjectIdAgentsAgentIdRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdAgentsAgentIdRoute: typeof ProjectIdAgentsAgentIdRoute
  ProjectIdAgentsNewRoute: typeof ProjectIdAgentsNewRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdAgentsAgentIdRoute: ProjectIdAgentsAgentIdRoute,
  ProjectIdAgentsNewRoute: ProjectIdAgentsNewRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
