/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId.index'
import { Route as ApiOnboardRouteImport } from './routes/api.onboard'
import { Route as ApiBlueprintRouteImport } from './routes/api.blueprint'
import { Route as ApiAgentChatRouteImport } from './routes/api.agent-chat'
import { Route as ApiActivityStreamRouteImport } from './routes/api.activity-stream'
import { Route as ProjectIdCallbackComposioRouteImport } from './routes/$projectId.callback.composio'
import { Route as ProjectIdAgentsNewRouteImport } from './routes/$projectId.agents.new'
import { Route as ProjectIdAgentsAgentIdRouteImport } from './routes/$projectId.agents.$agentId'

const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ApiOnboardRoute = ApiOnboardRouteImport.update({
  id: '/api/onboard',
  path: '/api/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintRoute = ApiBlueprintRouteImport.update({
  id: '/api/blueprint',
  path: '/api/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentChatRoute = ApiAgentChatRouteImport.update({
  id: '/api/agent-chat',
  path: '/api/agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityStreamRoute = ApiActivityStreamRouteImport.update({
  id: '/api/activity-stream',
  path: '/api/activity-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdCallbackComposioRoute =
  ProjectIdCallbackComposioRouteImport.update({
    id: '/callback/composio',
    path: '/callback/composio',
    getParentRoute: () => ProjectIdRoute,
  } as any)
const ProjectIdAgentsNewRoute = ProjectIdAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdAgentsAgentIdRoute = ProjectIdAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/api/activity-stream': typeof ApiActivityStreamRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/onboard': typeof ApiOnboardRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/agents/$agentId': typeof ProjectIdAgentsAgentIdRoute
  '/$projectId/agents/new': typeof ProjectIdAgentsNewRoute
  '/$projectId/callback/composio': typeof ProjectIdCallbackComposioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/activity-stream': typeof ApiActivityStreamRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/onboard': typeof ApiOnboardRoute
  '/$projectId': typeof ProjectIdIndexRoute
  '/$projectId/agents/$agentId': typeof ProjectIdAgentsAgentIdRoute
  '/$projectId/agents/new': typeof ProjectIdAgentsNewRoute
  '/$projectId/callback/composio': typeof ProjectIdCallbackComposioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/api/activity-stream': typeof ApiActivityStreamRoute
  '/api/agent-chat': typeof ApiAgentChatRoute
  '/api/blueprint': typeof ApiBlueprintRoute
  '/api/onboard': typeof ApiOnboardRoute
  '/$projectId/': typeof ProjectIdIndexRoute
  '/$projectId/agents/$agentId': typeof ProjectIdAgentsAgentIdRoute
  '/$projectId/agents/new': typeof ProjectIdAgentsNewRoute
  '/$projectId/callback/composio': typeof ProjectIdCallbackComposioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/api/activity-stream'
    | '/api/agent-chat'
    | '/api/blueprint'
    | '/api/onboard'
    | '/$projectId/'
    | '/$projectId/agents/$agentId'
    | '/$projectId/agents/new'
    | '/$projectId/callback/composio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/activity-stream'
    | '/api/agent-chat'
    | '/api/blueprint'
    | '/api/onboard'
    | '/$projectId'
    | '/$projectId/agents/$agentId'
    | '/$projectId/agents/new'
    | '/$projectId/callback/composio'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/api/activity-stream'
    | '/api/agent-chat'
    | '/api/blueprint'
    | '/api/onboard'
    | '/$projectId/'
    | '/$projectId/agents/$agentId'
    | '/$projectId/agents/new'
    | '/$projectId/callback/composio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
  ApiActivityStreamRoute: typeof ApiActivityStreamRoute
  ApiAgentChatRoute: typeof ApiAgentChatRoute
  ApiBlueprintRoute: typeof ApiBlueprintRoute
  ApiOnboardRoute: typeof ApiOnboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/api/onboard': {
      id: '/api/onboard'
      path: '/api/onboard'
      fullPath: '/api/onboard'
      preLoaderRoute: typeof ApiOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprint': {
      id: '/api/blueprint'
      path: '/api/blueprint'
      fullPath: '/api/blueprint'
      preLoaderRoute: typeof ApiBlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-chat': {
      id: '/api/agent-chat'
      path: '/api/agent-chat'
      fullPath: '/api/agent-chat'
      preLoaderRoute: typeof ApiAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity-stream': {
      id: '/api/activity-stream'
      path: '/api/activity-stream'
      fullPath: '/api/activity-stream'
      preLoaderRoute: typeof ApiActivityStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/callback/composio': {
      id: '/$projectId/callback/composio'
      path: '/callback/composio'
      fullPath: '/$projectId/callback/composio'
      preLoaderRoute: typeof ProjectIdCallbackComposioRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/agents/new': {
      id: '/$projectId/agents/new'
      path: '/agents/new'
      fullPath: '/$projectId/agents/new'
      preLoaderRoute: typeof ProjectIdAgentsNewRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/agents/$agentId': {
      id: '/$projectId/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/$projectId/agents/$agentId'
      preLoaderRoute: typeof ProjectIdAgentsAgentIdRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
  ProjectIdAgentsAgentIdRoute: typeof ProjectIdAgentsAgentIdRoute
  ProjectIdAgentsNewRoute: typeof ProjectIdAgentsNewRoute
  ProjectIdCallbackComposioRoute: typeof ProjectIdCallbackComposioRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdIndexRoute: ProjectIdIndexRoute,
  ProjectIdAgentsAgentIdRoute: ProjectIdAgentsAgentIdRoute,
  ProjectIdAgentsNewRoute: ProjectIdAgentsNewRoute,
  ProjectIdCallbackComposioRoute: ProjectIdCallbackComposioRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
  ApiActivityStreamRoute: ApiActivityStreamRoute,
  ApiAgentChatRoute: ApiAgentChatRoute,
  ApiBlueprintRoute: ApiBlueprintRoute,
  ApiOnboardRoute: ApiOnboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
