// Domain surface — stable, pure-TS API.
// Types/schemas, policy engine, catalog loaders, conversation helpers,
// connection interfaces. No db-client, no repository classes, no raw SDK factories.

export {
  getAgentDefinitionById,
  getPromptDefinitionById,
  getSkillDefinitionById,
  listAgentDefinitions,
  listPromptDefinitions,
  listSkillDefinitions,
} from "../catalog/index";
export type {
  ComposioAdapter,
  ComposioCatalogEntry,
  ComposioExecuteResult,
  ComposioRawTool,
} from "../connections/index";
export {
  buildConversationTranscript,
  CHECKPOINT_KEEP_RECENT_TOKENS,
  classifyEpisodicLesson,
  estimateConversationStateTokens,
  estimateTextTokens,
  extractRunInsights,
  extractStructuredConversationEvents,
  findCompactionBoundary,
  INLINE_COMPACTION_KEEP_RECENT_TOKENS,
  RECENT_MODEL_MESSAGE_LIMIT,
  RECENT_VISIBLE_MESSAGE_LIMIT,
  rehydrateConversationMessages,
  sanitizeConversationMessage,
  shouldAttemptChatMemoryDistillation,
  shouldInlineCompact,
  shouldRefreshCheckpoint,
} from "../conversation/runtime";
export { evaluatePolicy } from "../policy/engine";
export { detectAndSuggestLearnedRules } from "../policy/progressive-autonomy";
export { buildToolConfigEntry } from "../policy/tool-catalog";

export { listPromptSkills, type PromptSkill } from "../skills/index";
export {
  type AgentConfig,
  AgentConfigSchema,
  type AgentSchedule,
  AgentScheduleSchema,
  type AgentSessionRecord,
  AgentSessionSchema,
  type AgentSessionStatus,
  AgentSessionStatusSchema,
  type AgentTaskRecord,
  AgentTaskRecordSchema,
  type AgentToolContent,
  type AgentToolDefinition,
  type AgentToolResult,
  type ApprovalRecord,
  ApprovalRecordSchema,
  type ApprovalStatus,
  ApprovalStatusSchema,
  type ConversationCheckpoint,
  ConversationCheckpointSchema,
  type ConversationEvent,
  ConversationEventSchema,
  type ConversationThread,
  ConversationThreadSchema,
  type ContextSnapshotKind,
  ContextSnapshotKindSchema,
  type ContextSnapshotRecord,
  ContextSnapshotSchema,
  type LearnedPolicyRule,
  LearnedPolicyRuleSchema,
  type MetricObservation,
  MetricObservationSchema,
  type NotificationConfig,
  NotificationConfigSchema,
  type ProviderRequirement,
  ProviderRequirementSchema,
  type RunEvent,
  RunEventSchema,
  type RunRecord,
  type RunStatus,
  RunStatusSchema,
  type RunSummary,
  RunSummarySchema,
  type RunTrigger,
  RunTriggerSchema,
  type SandboxLeaseRecord,
  SandboxLeaseSchema,
  type SandboxLeaseStatus,
  SandboxLeaseStatusSchema,
  type SandboxProvider,
  SandboxProviderSchema,
  type ToolConfig,
  type ToolConfigEntry,
  ToolConfigEntrySchema,
  ToolConfigSchema,
  type ToolMode,
  ToolModeSchema,
  type WorkItemKind,
  WorkItemKindSchema,
  type WorkItemRecord,
  WorkItemSchema,
  type WorkItemStatus,
  WorkItemStatusSchema,
} from "../types/index";
