import { z } from "zod";

// ---------------------------------------------------------------------------
// ActionProposal — a proposed action generated by a Skill
// ---------------------------------------------------------------------------

export const ActionProposalSchema = z.object({
  /** Unique proposal identifier */
  id: z.string().min(1),
  /** Action name, e.g. "add_negative_keyword" */
  action: z.string().min(1),
  /** Tool category that will execute this action, e.g. "google_ads" */
  toolCategory: z.string().min(1),
  /** Arguments to pass to the tool */
  args: z.record(z.string(), z.unknown()),
  /** Human-readable explanation for why this action is proposed */
  reason: z.string().min(1),
  /** Confidence score between 0 and 1 inclusive */
  confidence: z.number().min(0).max(1),
  /** Which skill generated this proposal */
  skillSource: z.string().min(1),
  /** Whether this action can be undone */
  reversible: z.boolean(),
  /** Idempotency key to prevent duplicate execution */
  idempotencyKey: z.string().min(1),
});

export type ActionProposal = z.infer<typeof ActionProposalSchema>;

// ---------------------------------------------------------------------------
// ExecutionResult — the outcome of executing an ActionProposal
// ---------------------------------------------------------------------------

export const ExecutionResultSchema = z.object({
  /** The proposal that was executed */
  proposalId: z.string().min(1),
  /** Execution outcome */
  status: z.enum(["executed", "failed", "skipped"]),
  /** Output data from successful execution */
  output: z.record(z.string(), z.unknown()).optional(),
  /** Error message if execution failed */
  error: z.string().optional(),
  /** When the execution occurred */
  executedAt: z.date(),
});

export type ExecutionResult = z.infer<typeof ExecutionResultSchema>;
